services:
  db:
    container_name: postgres
    image: postgres:15    
    env_file: ".env"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
    expose:
      - "5432"

  app:
    build: ./app
    ports:
      - "80:80"
    env_file: ".env"
    environment:
      - DB_HOST=${db}
      - DB_NAME=${POSTGRES_DB}
      - DB_USER=${POSTGRES_USER}
      - DB_PASS=${POSTGRES_PASSWORD}
    depends_on:
      - db
    restart: always